### PR TITLE
SDK Refactor

### PR DESCRIPTION
**Pull request by jsmartt**
This PR:
- Strips out the REST client functionality, replacing it with the oneview-sdk library, which is much fuller-featured and well-tested
- Namespaces everything under the `OneviewChefProvisioningDriver` module
- Allows more (& better) credential options (while still supporting the existing knife params)
- Enables more Rubocop rules, getting rid of lazy code
- Updates documentation to me more clear
- Bumps version to 1.3.0

Although it's huge, it just replaces the OneView REST client functionality. We're still using the same ICSP request methods; we can refactor those in the future.

Note that this should not break existing functionality for users; it just updates how it's handled under the hood and provides users more configuration options.

### CODE REVIEW

**Comment by jsmartt** [comment]
@thebsdbox , any chance you've had a chance to validate this at all?

**Comment by jsmartt** [comment]
@thebsdbox , any chance you've had a chance to validate this at all?

**Comment by thebsdbox** [comment]
Had no lab access due to a relocation from Grenoble -> Geneva and my personal lab access was broken. Finally had all that resolved last week, hence trying to get some real testing done. 

I should get chance to have a proper look at the issue and the code refactor, although from the testing I'd had chance to do it lgtm.

**Comment by jsmartt** [comment]
No worries. It's hard for me to get access to a lab myself. Thanks Dan!

**Comment by tmiotto** [comment]
@jsmartt Does any kind of work is needed here in this PR? Or do we just need to test it against physical hardware?

**Comment by jsmartt** [comment]
@tmiotto , I think just the testing against real HW for now. We may want to update things later, but this PR is already big enough; I don't want to include logic changes at the same time.

**Comment by tmiotto** [comment]
@jsmartt I don't know exactly if this is a problem but... I tried to use it with chef-zero and:

1. If I create a knife file it tries to connect and authenticate ethernally with a chef server (That actually does not exist)
2. If I delete the 'my_chef_server_url' it won't work.
3. If I delete the `knife.rb` I need to use the ENV vars, that work well for OneView, but they don't support ICsP...
4. Then I had to change my plans, and pass the oneview and icsp info along the machine_options, but surprisingly it didn't work.

Well, there's  a lot of room for improvement there, and I couldn't use it with the chef-zero... Did I miss something there?

**Comment by jsmartt** [comment]
@tmiotto , I think it would be good to support ICsp ENV variables at some point, but there's plenty of other refactoring that needs done to the ICsp libraries also. I wanted to avoid that in the PR to keep it a little smaller.

**Pull request merged**
