### PR TITLE
Fork branch

### PR DESCRIPTION
**Pull request by jsmartt**
**Still not quite ready**, but this is a continuation of #47 

Additional capabilities added:

Ability to use :allocate action to provision only a server profile (:converge will provision OS and install client).
Server location affinity, gives the ability to use a recipe to specify a particular server for a particular use case e.g. :server_location => 'enc1, bay1'
Insight Control Server Provisioning is no longer a requirement, Chef warnings will be generated for missing configuration and if :converge action is used however it will safely provision a server profile. This change allows the use of the HPE Data centre simulator
Added the ability to use a timeout in the knife.rb for connectivity (for debug/testing and network testing issues)
Additional error generation and logic dependant of actions added also.

### CODE REVIEW

**Comment by jsmartt** [comment]
@thebsdbox , I made some updates, added a few tests, and simplified a few things. However, I haven't gotten a chance to test it thoroughly yet. I can test it out on my DCS next week, but if you wouldn't mind doing some tests on real HW that would be great too.
Thanks!

**Comment by thebsdbox** [comment]
I've tested with the DCS (laptop) and with physical C7000/OneView in the Grenoble DataCentre. 

DCS:
Works fine without ICSP configuration to allocate/destroy/converge servers. However the only problem is the destroy_machine method, the check for icsp_ignore doesn't work this means that calls the ridley methods to remove the chef client from the server, resulting in a connection error and some warnings about unfinished processes:
```
W, [2016-05-14T16:35:17.808849 #12236]  WARN -- : Terminating task: type=:finalizer, meta={:method_name=>:__shutdown__}, status=:receiving
	Celluloid::TaskFiber backtrace unavailable. Please try `Celluloid.task_class = Celluloid::TaskThread` if you need backtraces here.
W, [2016-05-14T16:35:17.809970 #12236]  WARN -- : Terminating task: type=:finalizer, meta={:method_name=>:__shutdown__}, status=:receiving
	Celluloid::TaskFiber backtrace unavailable. Please try `Celluloid.task_class = Celluloid::TaskThread` if you need backtraces here.
W, [2016-05-14T16:35:17.810592 #12236]  WARN -- : Terminating task: type=:finalizer, meta={:method_name=>:__shutdown__}, status=:receiving
	Celluloid::TaskFiber backtrace unavailable. Please try `Celluloid.task_class = Celluloid::TaskThread` if you need backtraces here.
```
Also the newline before the ICSP warnings was removed, this results in the warning being appended to chef output about allocating etc.. (it's a purely aesthetic thing)

C7000:
Everything is working perfect... running an allocate recipe will return in about 12 seconds, leaving OneView to complete all of the configuration work in the background. Using the same recipe with the action set to `:converge` will continue on with an allocated server and simply perform the ICSP steps. 

Running a `:converge` on a completely blank server has the same outcomes as the code before any changes were made, so the logic for all of the ICSP testing is correct etc.

I'll try to get you access to the physical equipment I used today, alternatively there is another lab I have access too. 

Conclusion:
Almost ready from my perspective :-)

**Comment by jsmartt** [comment]
Ok @thebsdbox sorry for the delay, but I think may finally be ready. I actually removed the sections from the destroy_machine method that removed the client and node from the Chef server altogether. Chef is actually supposed to take care of this automatically, and that was just in there because it wasn't doing so previously. It is deleting things automatically now, so we don't even need the ridley gem as a dependency now.

Let me know what you think of it now.

**Comment by thebsdbox** [comment]
Hi @jsmartt I've just tested it on DCS/PHYS with my recipe for populating a full enclosure, and then wiping various profiles from various hardware. From my perspective it's ready to be merged, no errors and everything completed successfully.

**Pull request merged**
